server:
  port: 8080
  model: debug
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: ginm1
  username: root
  password: 123123
  charset: utf8
myLog:
  path: ./log
  name: sys
  #控制台 console 文件file
  model: console
